-- Core users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  password text,
  phone text,
  nic_number text,
  district text,
  province text,
  ds_division text,
  preferred_language text,
  age_group text,
  known_bee_allergy text,
  blood_group text,
  beekeeping_nature text,
  business_reg_no text,
  primary_bee_species text,
  nvq_level text,
  role text,
  years_experience integer,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists users_email_unique on users (lower(email));

-- Apiaries
create table if not exists apiaries (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  district text,
  area text,
  established_date date,
  status text,
  apiary_type text,
  terrain text,
  forage_primary text,
  blooming_window text,
  gps_latitude numeric,
  gps_longitude numeric,
  notes text,
  landlord_name text,
  landlord_contact text,
  contract_start date,
  contract_end date,
  rental_fee numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Hives
create table if not exists hives (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  apiary_id bigint,
  name text not null,
  hive_type text,
  location_type text,
  status text,
  queen_present integer default 0,
  queen_age integer,
  queen_age_risk text,
  colony_strength text,
  last_inspection_date date,
  inspection_overdue integer,
  pest_detected integer,
  pest_reported_date date,
  is_starred integer default 0,
  is_flagged integer default 0,
  flag_reason text,
  gps_latitude numeric,
  gps_longitude numeric,
  notes text,
  num_frames integer,
  num_supers integer,
  brood_box_type text,
  pot_material text,
  pot_volume_liters numeric,
  entrance_size text,
  log_length_cm numeric,
  log_diameter_cm numeric,
  wood_type text,
  stingless_species text,
  colony_size text,
  propolis_type text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Inspections
create table if not exists inspections (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  apiary_id bigint,
  inspection_date date not null,
  queen_presence text,
  honey_pollen_stores text,
  pest_disease_presence text[],
  pest_name text,
  pest_treatment_status text,
  treatment_used text,
  active_frame_count integer,
  queen_cell_presence text,
  bottom_board_cleaned text,
  general_remarks text,
  queen_present integer,
  colony_strength text,
  pest_detected integer,
  notes text,
  created_at timestamptz default now()
);

-- Pot hive inspections
create table if not exists pot_hive_inspections (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  apiary_id bigint,
  inspection_date date not null,
  entrance_activity text,
  queen_presence text,
  honey_pollen_stores text,
  pest_disease_presence text[],
  pest_names text,
  treatment_status text,
  treatment_used text,
  general_remarks text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Hive details
create table if not exists feedings (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  feeding_date date not null,
  feed_type text not null,
  quantity numeric,
  unit text,
  concentration text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists hive_components (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  component_type text not null,
  quantity integer not null,
  condition text not null,
  installed_date date,
  notes text,
  created_at timestamptz default now()
);

create table if not exists queens (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  marking_color text,
  source text,
  introduction_date date,
  status text not null,
  species text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists treatments (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint not null,
  treatment_date date not null,
  treatment_type text not null,
  product_name text,
  dosage text,
  application_method text,
  duration_days integer,
  end_date date,
  outcome text,
  notes text,
  created_at timestamptz default now()
);

-- Harvests
create table if not exists harvests (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint,
  apiary_id bigint,
  harvest_date date not null,
  harvest_type text not null,
  quantity numeric not null,
  unit text not null,
  quality text,
  harvest_method text,
  surplus_listed integer default 0,
  notes text,
  created_at timestamptz default now()
);

-- Finance
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  user_id bigint,
  hive_id bigint,
  apiary_id bigint,
  expense_date date not null,
  expense_type text not null,
  amount numeric not null,
  description text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists income (
  id bigint generated by default as identity primary key,
  user_id bigint,
  harvest_id bigint,
  income_date date not null,
  income_type text not null,
  amount numeric not null,
  buyer_name text,
  description text,
  notes text,
  created_at timestamptz default now()
);

-- Colony transfers
create table if not exists colony_transfers (
  id bigint generated by default as identity primary key,
  user_id bigint,
  source_hive_id bigint not null,
  target_hive_id bigint not null,
  transfer_date date not null,
  transfer_type text,
  queen_moved integer default 0,
  brood_frames_moved integer default 0,
  notes text,
  created_at timestamptz default now()
);

-- Client services
create table if not exists client_services (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  client_name text not null,
  client_contact text,
  client_email text,
  service_type text,
  description text,
  location text,
  gps_latitude numeric,
  gps_longitude numeric,
  assigned_to bigint,
  status text,
  priority text,
  scheduled_date date,
  completed_date date,
  payment_amount numeric,
  payment_status text,
  expense_proof_required integer,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Notifications and alerts
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  target_role text,
  notification_type text,
  severity text,
  title text,
  message text,
  related_type text,
  related_id bigint,
  is_read integer default 0,
  is_dismissed integer default 0,
  created_at timestamptz default now()
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  alert_type text,
  message text,
  is_read integer default 0,
  created_at timestamptz default now()
);

-- Apiary history
create table if not exists apiary_history (
  id bigint generated by default as identity primary key,
  apiary_id bigint not null,
  user_id bigint not null,
  action text,
  details text,
  created_at timestamptz default now()
);

-- Landowner plots and contracts
create table if not exists landowner_plots (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  province text,
  district text,
  ds_division text,
  gps_latitude numeric,
  gps_longitude numeric,
  total_acreage numeric,
  forage_entries jsonb default '[]',
  water_availability text,
  shade_profile text,
  vehicle_access text,
  night_access boolean default false,
  images jsonb default '[]',
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists landowner_listings (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  plot_id bigint not null,
  listing_code text,
  financial_terms text,
  cash_rent_lkr numeric,
  honey_share_kgs numeric,
  spraying_clause_agreed boolean default false,
  status text,
  availability_end_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists landowner_contracts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  listing_id bigint,
  bid_id bigint,
  plot_id bigint,
  beekeeper_name text,
  plot_name text,
  hive_count integer,
  status text,
  cash_rent_lkr numeric,
  honey_share_kgs numeric,
  financial_terms text,
  move_out_requested_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Helpful indexes
create index if not exists apiaries_user_id_idx on apiaries (user_id);
create index if not exists hives_user_id_idx on hives (user_id);
create index if not exists inspections_user_id_idx on inspections (user_id);
create index if not exists pot_hive_inspections_user_id_idx on pot_hive_inspections (user_id);
create index if not exists feedings_user_id_idx on feedings (user_id);
create index if not exists hive_components_user_id_idx on hive_components (user_id);
create index if not exists queens_user_id_idx on queens (user_id);
create index if not exists treatments_user_id_idx on treatments (user_id);
create index if not exists harvests_user_id_idx on harvests (user_id);
create index if not exists expenses_user_id_idx on expenses (user_id);
create index if not exists income_user_id_idx on income (user_id);
create index if not exists colony_transfers_user_id_idx on colony_transfers (user_id);
create index if not exists client_services_user_id_idx on client_services (user_id);
create index if not exists notifications_user_id_idx on notifications (user_id);
create index if not exists alerts_user_id_idx on alerts (user_id);
create index if not exists apiary_history_user_id_idx on apiary_history (user_id);
create index if not exists landowner_plots_user_id_idx on landowner_plots (user_id);
create index if not exists landowner_listings_user_id_idx on landowner_listings (user_id);
create index if not exists landowner_contracts_user_id_idx on landowner_contracts (user_id);
